apiVersion: maximilianopizarro.github.io/v1alpha1
kind: PyhipsterWorker
metadata:
  name: pyhipster-worker
spec:
  enabled: true
  instanceBaseName: demo
  replicas: 1
  port: 8082
  timeoutSeconds: 600
  image:
    repository: quay.io/maximilianopizarro/jhipster-online-pyhipster-worker
    tag: "2.41.1-pyhipster-worker"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
